fastlane_version '2.216.0 '

before_all do
  # ensure_git_branch
  # ensure_git_status_clean
  # git_pull
end

platform :ios do
  # iOS Lanes

  desc "Run SwiftLint to check for code style violations"
  lane :lint do
    swiftlint(
      mode: :lint,
      output_file: "swiftlint_report.json",
      ignore_exit_status: true,
      config_file: ".swiftlint.yml",
      reporter: "json",
      quiet: true,
      strict: true)
  end

  desc "Build the app"
  lane :build do
    ENV['FASTLANE_XCODE_LIST_TIMEOUT'] = '300'
    ENV['FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT'] = '300'
    ENV['FASTLANE_XCODEBUILD_SETTINGS_RETRIES'] = '20'
    ENV['FASTLANE_EXPLICIT_OPEN_SIMULATOR'] = '1'
    setup_ci(force: true) if ENV['CI']
    match(type: 'development', app_identifier: 'com.jerryokafor.networth', readonly: true)
    scan(
      project: './iosApp/iosApp.xcodeproj',
      scheme: 'iosApp',
      configuration: "Debug",
      clean: true,
      sdk: 'iphoneos',
      device: 'iPhone 12 Pro',
      build_for_testing: true,
      derived_data_path: "fastlane/iosBuild/data"
      )
    end

  desc "Run tests"
  lane :test do
    ENV['FASTLANE_XCODE_LIST_TIMEOUT'] = '300'
    ENV['FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT'] = '300'
    ENV['FASTLANE_XCODEBUILD_SETTINGS_RETRIES'] = '20'
    ENV['FASTLANE_EXPLICIT_OPEN_SIMULATOR'] = '1'
    setup_ci(force: true) if ENV['CI']
    match(type: 'development', app_identifier: 'com.jerryokafor.networth', readonly: true)

    scan(
      project: './iosApp/iosApp.xcodeproj',
      scheme: 'iosApp',
      clean: false,
      configuration: "Debug",
      sdk: 'iphoneos',
      code_coverage: true,
      device: 'iPhone 12 Pro',
      prelaunch_simulator: true,
      test_without_building: true,
      derived_data_path: "fastlane/iosBuild/data"
      )
    end
end


platform :android do
  # Android Lanes
  lane :beta do
    gradle(task: ':android:clean')
      gradle(
        task: ':android:assemble',
        build_type: 'Release'
      )
    end
end