name: Build NetWorth (Build Test & Check)

on: push

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-quality:
    name: Verify Code Quality
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Code Quality
        run: ./gradlew detekt ktlintCheck

  build-android:
    name: Build, Test & Check (Android)
    runs-on: macos-latest
    needs: [ code-quality ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Run Shared Unit Tests (Android)
        run: ./gradlew cleanTestDebugUnitTest testDebugUnitTest

      - name: Build android app
        run: ./gradlew assembleDebug

      - name: Run Android Unit Tests
        run: ./gradlew :androidApp:testDebugUnitTest

      - name: Run Lint
        run: ./gradlew :androidApp:lintDebug

  build-ios:
    name: Build, Test & Check (iOS)
    runs-on: macos-13
    needs: [ code-quality ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Setup Team Account
        env:
          TEAM_ID: ${{ secrets.TEAM_ID }}
        run: |
          touch "iosApp/Configuration/Config.xcconfig"
          echo "TEAM_ID=$TEAM_ID" >>iosApp/Configuration/Config.xcconfig
          echo "BUNDLE_ID=com.jerryokafor.networth" >>iosApp/Configuration/Config.xcconfig
          echo "APP_NAME=NetWorth" >>iosApp/Configuration/Config.xcconfig
          cat iosApp/Configuration/Config.xcconfig


      - name: Run shared Unit Tests (iOS)
        run: ./gradlew cleanIosX64Test iosX64Test

      - name: Build iOS app
        run: |
          xcodebuild \
            -project iosApp/iosApp.xcodeproj \
            -configuration Debug \
            -scheme iosApp \
            -sdk iphoneos \
            -destination name='iPhone 14 Pro' \
            build

      - name: Run iOS unit tests
        run: |
          xcodebuild clean test \
            -project iosApp/iosApp.xcodeproj \
            -configuration Debug \
            -scheme iosApp \
            -sdk iphoneos \
            -destination name='iPhone 14 Pro' \
            -test-timeouts-enabled YES \
            build